# Generated by Django 3.0.3 on 2020-03-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('valid', models.CharField(blank=True, choices=[('', '未选择'), ('1', '有效'), ('0', '无效')], default='1', max_length=10)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('charge_type', models.CharField(choices=[('bal', '充值余额'), ('be_normal', '升级为会员'), ('be_vip', '升级为VIP'), ('be_proxy', '升级为代理')], default='bal', max_length=50)),
                ('order_id', models.CharField(blank=True, max_length=50)),
                ('amt', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('done', '已到账')], default='pending', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('valid', models.CharField(blank=True, choices=[('', '未选择'), ('1', '有效'), ('0', '无效')], default='1', max_length=10)),
                ('code_type', models.CharField(blank=True, max_length=50)),
                ('code_type_name', models.CharField(blank=True, max_length=50)),
                ('code_value', models.CharField(blank=True, max_length=50)),
                ('code_value_name', models.CharField(blank=True, max_length=50)),
                ('idx', models.IntegerField(default=0)),
                ('code_group', models.CharField(blank=True, max_length=50)),
                ('code_group_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('valid', models.CharField(blank=True, choices=[('', '未选择'), ('1', '有效'), ('0', '无效')], default='1', max_length=10)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('express_type', models.CharField(blank=True, max_length=50)),
                ('send_addr', models.CharField(blank=True, max_length=50)),
                ('receive_addr', models.CharField(blank=True, max_length=50)),
                ('sender', models.CharField(blank=True, max_length=50)),
                ('receiver', models.CharField(blank=True, max_length=50)),
                ('amt', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('pending', '已下单（未发货）'), ('done', '已发货')], default='pending', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('valid', models.CharField(blank=True, choices=[('', '未选择'), ('1', '有效'), ('0', '无效')], default='1', max_length=10)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('user_type', models.CharField(choices=[('normal', '普通会员'), ('vip', 'VIP'), ('proxy', '代理会员')], default='normal', max_length=50)),
                ('tel', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('bal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('avatar', models.FileField(blank=True, upload_to='avatar')),
                ('reference', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
