# Generated by Django 3.0.3 on 2020-03-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='qq',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='wx',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
