# Generated by Django 3.0.3 on 2020-03-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_validateimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumeinfo',
            name='receiver_postid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consumeinfo',
            name='receiver_tel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consumeinfo',
            name='sender_postid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consumeinfo',
            name='sender_tel',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
