# Generated by Django 3.0.3 on 2020-03-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_consumeinfo_express_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('valid', models.CharField(blank=True, choices=[('', '未选择'), ('1', '有效'), ('0', '无效')], default='1', max_length=10)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('addr_type', models.CharField(blank=True, choices=[('send', '发货地址')], default='send', max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('tel', models.CharField(blank=True, max_length=50)),
                ('postid', models.CharField(blank=True, max_length=50)),
                ('is_default', models.CharField(blank=True, default='0', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
