# Generated by Django 3.0.3 on 2020-03-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_addressinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='def_express',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
