# Generated by Django 3.0.3 on 2020-03-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20200315_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('valid', models.CharField(blank=True, choices=[('', '未选择'), ('1', '有效'), ('0', '无效')], default='1', max_length=10)),
                ('corp', models.CharField(blank=True, max_length=50)),
                ('corp_name', models.CharField(blank=True, max_length=50)),
                ('express_type', models.CharField(blank=True, max_length=50)),
                ('express_name', models.CharField(blank=True, max_length=50)),
                ('lv1', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('lv2', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('lv3', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
