# Generated by Django 3.0.3 on 2020-03-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_orgmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('valid', models.CharField(blank=True, choices=[('', '未选择'), ('1', '有效'), ('0', '无效')], default='1', max_length=10)),
                ('excel', models.FileField(blank=True, upload_to='excel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
