# Generated by Django 3.0.3 on 2020-03-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_excellist'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumeinfo',
            name='ec_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
