# Generated by Django 3.0.3 on 2020-03-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_consumeinfo_ec_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumeinfo',
            name='goods_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
