# Generated by Django 3.0.3 on 2020-03-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_consumeinfo_goods_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressinfo',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='prov',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consumeinfo',
            name='receive_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consumeinfo',
            name='receive_county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consumeinfo',
            name='receive_prov',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consumeinfo',
            name='send_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consumeinfo',
            name='send_county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consumeinfo',
            name='send_prov',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
