# Generated by Django 3.0.3 on 2020-03-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20200316_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.CharField(choices=[('custom', '普通会员'), ('admin', '管理员')], default='custom', max_length=50),
        ),
    ]
