# Generated by Django 3.0.3 on 2020-04-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20200401_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('valid', models.CharField(blank=True, choices=[('', '未选择'), ('1', '有效'), ('0', '无效')], default='1', max_length=10)),
                ('content', models.CharField(blank=True, max_length=50)),
                ('end_date', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
