# Generated by Django 3.0.3 on 2020-04-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20200401_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=16),
        ),
    ]
