# Generated by Django 3.0.3 on 2020-04-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20200401_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmap',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
