# Generated by Django 3.0.3 on 2020-04-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20200401_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpdateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('valid', models.CharField(blank=True, choices=[('', '未选择'), ('1', '有效'), ('0', '无效')], default='1', max_length=10)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('kf_user_id', models.CharField(blank=True, max_length=50)),
                ('update_col', models.CharField(blank=True, max_length=50)),
                ('before_update', models.CharField(blank=True, max_length=500)),
                ('after_update', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='consumeinfo',
            name='task_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
