# Generated by Django 3.0.3 on 2020-04-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_auto_20200408_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumeinfo',
            name='batch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumeinfo',
            name='idx',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consumeinfo',
            name='status',
            field=models.CharField(choices=[('fail', '已提交'), ('pending', '未发货'), ('done', '已发货'), ('finish', '已签收')], default='pending', max_length=50),
        ),
    ]
