# Generated by Django 3.0.3 on 2020-04-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_auto_20200410_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumeinfo',
            name='batch',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
